controllers:
  resource: ../src/Controller/
  type: attribute

app_login:
  path: /
  controller: App\Controller\Auth\SecurityController::login

api_contacts:
  path: /api/contacts
  controller: App\Controller\PostData\ContactController::receiveContactData
  methods: POST
